---
- hosts: public_nodes
  become: yes
  vars:
    wordpress_path: /var/www/wordpress
    private_node_ip: 172.31.17.67
    telegraf_url: https://dl.influxdata.com/telegraf/releases/telegraf-1.8.3-1.x86_64.rpm
    grafana_url: https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana-5.3.4-1.x86_64.rpm
  tasks:
    - include_tasks: tasks/public/os-dependencies.yml
    - include_tasks: tasks/public/install-wordpress.yml
    - include_tasks: tasks/public/install-telegraf.yml
    - include_tasks: tasks/public/install-grafana.yml
- hosts: private_nodes
  become: yes
  vars:
    public_node_ip: 172.31.28.179
    influxdb_url: https://dl.influxdata.com/influxdb/releases/influxdb-1.7.1.x86_64.rpm
  tasks:
    - include_tasks: tasks/private/os-dependencies.yml
    - include_tasks: tasks/private/create-wordpress-database.yml
    - include_tasks: tasks/private/install-influxdb.yml