---
- hosts: metrics_source
  become: yes
  vars:
    telegraf_url: https://dl.influxdata.com/telegraf/releases/telegraf-1.8.3-1.x86_64.rpm
    metrics_store_ip: 172.31.19.113
  tasks:
    - name: "Test source"
      debug:
        msg: "Source OK"
    - name: "Install Telegraf"
      yum:
        name: "{{telegraf_url}}"
        state: present
    - name: "Copy Telegraf config"
      template:
        src: templates/telegraf.conf
        dest: /etc/telegraf/telegraf.conf
    - name: "Start Telegraf"
      service:
        name: "telegraf"
        state: restarted
- hosts: metrics_store
  become: yes
  vars:
    influxdb_url: https://dl.influxdata.com/influxdb/releases/influxdb-1.7.1.x86_64.rpm
  tasks:
    - name: "Test Store"
      debug:
        msg: "Store OK"
    - name: "Install InfluxDB"
      yum:
        name: "{{influxdb_url}}"
        state: present
    - name: "Start InfluxDB"
      service:
        name: "influxdb"
        state: restarted
- hosts: metrics_graph
  tasks:
    - name: "Test Graph"
      debug:
        msg: "Graph OK"