---
- hosts: wordpress_nodes
  become: yes
  tasks:
    - name: "Install packages"
      yum:
        name: "{{packages}}"
        state: present
      vars:
        packages:
          - httpd
          - mariadb
          - mariadb-server
          - php
          - php-mysql
          - MySQL-python
    - name: "Download Wordpress"
      get_url:
        url: https://wordpress.org/latest.zip
        dest: /tmp/wp.zip
    - name: "Unpack wordpress"
      unarchive:
        src: /tmp/wp.zip
        dest: /var/www/
        remote_src: yes
    - name: "Start MariaDB"
      service:
        name: "{{services}}"
        state: started
      vars:
        services:
          - httpd
          - mariadb
    - name: "Add database for wordpress"
      mysql_db:
        name: wp_db
        state: present