---
- name: "Start MariaDB"
  service:
    name: mariadb
    state: started
- name: "Create database user"
  mysql_user:
    name: wordpress
    password: MatiGlita123
    priv: '*.*:ALL'
    host: '%'
    state: present
- name: "Add database for wordpress"
  mysql_db:
    name: wp_db
    state: present