---
- name: "Install Grafana"
  yum:
    name: "{{grafana_url}}"
    state: present
- name: "Copy Grafana config"
  template:
    src: templates/public/grafana.ini
    dest: /etc/grafana/grafana.ini
- name: "Start Grafana"
  service:
    name: "grafana-server"
    state: restarted
- name: "Create datasource for Grafana"
  grafana_datasource:
    name: "influxdb"
    grafana_url: "http://127.0.0.1:8080"
    grafana_user: "admin"
    grafana_password: "admin"
    org_id: "1"
    ds_type: "influxdb"
    url: "http://{{private_node_ip}}:8086"
    database: "metrics"
    is_default: yes
    tls_skip_verify: yes