---
- name: "Install Telegraf"
  yum:
    name: "{{telegraf_url}}"
    state: present
- name: "Copy Telegraf config"
  template:
    src: templates/public/telegraf.conf
    dest: /etc/telegraf/telegraf.conf
- name: "Start Telegraf"
  service:
    name: "telegraf"
    state: restarted